name: Code Style

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Check for leftover println
        run: ./tests/left_over_println.sh
      - name: Check formatting
        run: cargo fmt --all -- --check
